const baseGitResponse = {
  sha: "03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
  node_id: "C_kwDOKDf_u9oAKDAzYTdhYjVjZTE2MmNiMWIyN2QyZTQ2NzE0MTg4Mjg2ZTZjOWFhM2Y",
  commit: {
    author: {
      name: "Kewal Rathod",
      email: "kewalrathod8@gmail.com",
      date: "2023-08-10T11:18:08Z",
    },
    committer: {
      name: "Kewal Rathod",
      email: "kewalrathod8@gmail.com",
      date: "2023-08-10T11:18:08Z",
    },
    message: "* Fixed issues with Single Select.",
    tree: {
      sha: "c9f38b2dfe6698106f9a9326cdbd1b575e5d8c79",
      url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/git/trees/c9f38b2dfe6698106f9a9326cdbd1b575e5d8c79",
    },
    url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/git/commits/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
    comment_count: 0,
    verification: {
      verified: false,
      reason: "unsigned",
      signature: null,
      payload: null,
    },
  },
  url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/commits/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
  html_url: "https://github.com/Kewal89/multiselect-pure-js/commit/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
  comments_url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/commits/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/comments",
  author: {
    login: "Kewal89",
    id: 43823249,
    node_id: "MDQ6VXNlcjQzODIzMjQ5",
    avatar_url: "https://avatars.githubusercontent.com/u/43823249?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Kewal89",
    html_url: "https://github.com/Kewal89",
    followers_url: "https://api.github.com/users/Kewal89/followers",
    following_url: "https://api.github.com/users/Kewal89/following{/other_user}",
    gists_url: "https://api.github.com/users/Kewal89/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Kewal89/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Kewal89/subscriptions",
    organizations_url: "https://api.github.com/users/Kewal89/orgs",
    repos_url: "https://api.github.com/users/Kewal89/repos",
    events_url: "https://api.github.com/users/Kewal89/events{/privacy}",
    received_events_url: "https://api.github.com/users/Kewal89/received_events",
    type: "User",
    site_admin: false,
  },
  committer: {
    login: "Kewal89",
    id: 43823249,
    node_id: "MDQ6VXNlcjQzODIzMjQ5",
    avatar_url: "https://avatars.githubusercontent.com/u/43823249?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Kewal89",
    html_url: "https://github.com/Kewal89",
    followers_url: "https://api.github.com/users/Kewal89/followers",
    following_url: "https://api.github.com/users/Kewal89/following{/other_user}",
    gists_url: "https://api.github.com/users/Kewal89/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Kewal89/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Kewal89/subscriptions",
    organizations_url: "https://api.github.com/users/Kewal89/orgs",
    repos_url: "https://api.github.com/users/Kewal89/repos",
    events_url: "https://api.github.com/users/Kewal89/events{/privacy}",
    received_events_url: "https://api.github.com/users/Kewal89/received_events",
    type: "User",
    site_admin: false,
  },
  parents: [
    {
      sha: "ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
      url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/commits/ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
      html_url: "https://github.com/Kewal89/multiselect-pure-js/commit/ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
    },
  ],
  stats: {
    total: 73,
    additions: 51,
    deletions: 22,
  },
  files: [
    {
      sha: "aba9f24292849492f4a5ec3743a9a1fb01d2c6cd",
      filename: "index.html",
      status: "modified",
      additions: 4,
      deletions: 3,
      changes: 7,
      blob_url: "https://github.com/Kewal89/multiselect-pure-js/blob/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/index.html",
      raw_url: "https://github.com/Kewal89/multiselect-pure-js/raw/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/index.html",
      contents_url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/contents/index.html?ref=03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
      patch:
        '@@ -52,7 +52,7 @@\n           }\n         })\n \n-        const itemList3 = Array.from({ length: 100000 }, (_, i) => {\n+        const itemList3 = Array.from({ length: 2 }, (_, i) => {\n           return {\n             index: i,\n             label: `Item ${i}`,\n@@ -134,14 +134,15 @@\n           items: itemList3,\n           rootElement: ".MultiSelectContainer_3",\n           disabledFields: [31, 32, 33, 34],\n-          defaultSelected: [0, 1, 2, 3, 4, 5, 6],\n+          defaultSelected: [0, 1, 2, 3, 4, 5],\n+          mode: "single",\n+          debug: true,\n         })\n         multiSelect4 = new MultiSelect({\n           items: itemList4,\n           rootElement: ".MultiSelectContainer_4",\n           mode: "single",\n           defaultSelected: [0],\n-          debug: true,\n         })\n         multiSelect5 = new MultiSelect({\n           items: itemList3,',
    },
    {
      sha: "748d66ad26de2cf09b8ceb224148ca3e4cb2a481",
      filename: "multiselect.css",
      status: "modified",
      additions: 2,
      deletions: 2,
      changes: 4,
      blob_url: "https://github.com/Kewal89/multiselect-pure-js/blob/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/multiselect.css",
      raw_url: "https://github.com/Kewal89/multiselect-pure-js/raw/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/multiselect.css",
      contents_url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/contents/multiselect.css?ref=03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
      patch:
        "@@ -319,9 +319,9 @@\n   color: #B5BDC1;\n }\n \n-.MultiSelectList .VItem:last-child:hover {\n+/* .MultiSelectList .VItem:last-child:hover {\n   border-radius: 0 0 8px 8px;\n-}\n+} */\n \n .MultiSelectList .VItem:hover {\n   background: #E7E9EA;",
    },
    {
      sha: "7ee41e8994b3cae7f8a4b36e73ac65d31c9cff50",
      filename: "multiselect.js",
      status: "modified",
      additions: 44,
      deletions: 17,
      changes: 61,
      blob_url: "https://github.com/Kewal89/multiselect-pure-js/blob/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/multiselect.js",
      raw_url: "https://github.com/Kewal89/multiselect-pure-js/raw/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/multiselect.js",
      contents_url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/contents/multiselect.js?ref=03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
      patch:
        '@@ -39,6 +39,10 @@ function MultiSelect(props) {\n   this.unselectedItems = Array.isArray(this.defaultSelected) && this.defaultSelected.length > 0 ? [] : [...this.itemList]\n   // TODO: Handle This Error Properly As It May Crash Rest of The Code.\n   if (!Array.isArray(this.itemList)) console.error("Item List should be an array.", this.root)\n+  if (this.mode === "single" && this.defaultSelected.length > 1) {\n+    this.defaultSelected = [this.defaultSelected[0]]\n+    console.error("Single Select Accepts only 1 value in defaultSelected")\n+  }\n \n   this.initialize()\n   multiSelectInstances.set(this.rootContainer, this)\n@@ -68,9 +72,12 @@ MultiSelect.prototype.recalculateHeight = function () {\n     else isClearAll.classList.add("Inactive")\n   }\n \n-  if (!this.chipCollapse || this.selectedItems.length < this.collapseChipCount) return false\n-  const height = this.popperContainer.querySelector(".ChipsList").offsetHeight\n-  this.unselectedItemsContainer.style.height = `${this.height - height}px`\n+  if (!this.chipCollapse) return false\n+  var height = 400\n+  if (this.itemList.length < 10) height = this.itemList.length * 40\n+  else height = this.height - this.popperContainer.querySelector(".ChipsList").offsetHeight\n+\n+  this.unselectedItemsContainer.style.height = `${height}px`\n }\n \n MultiSelect.prototype.generateDOM = function () {\n@@ -232,7 +239,7 @@ MultiSelect.prototype.setupEventListeners = function () {\n     self.backdropElement.classList.toggle("Show", !isOpen)\n \n     if (self.virtualList) {\n-      self.refreshList()\n+      // self.refreshList()\n     }\n   }\n \n@@ -266,7 +273,7 @@ MultiSelect.prototype.setupEventListeners = function () {\n       if (!self.outerLabelCollapse) self.renderSelectedItems() // No Overflow\n     } else if (event.target.classList.contains("VItem") && !event.target.closest(".ChipsList")) {\n       self.handleItemSelection(event.target)\n-    } else if (event.target.classList.contains("VItemCrossIcon")) {\n+    } else if (event.target.classList.contains("VItemCrossIcon") && self.mode === "multi") {\n       self.handleItemUnselection(event.target.closest(".VItem"))\n     } else if (self.mode === "multi" && event.target === self.selectAllBtn && self.selectAllExpose) {\n       self.selectAllItems()\n@@ -305,11 +312,26 @@ MultiSelect.prototype.addTooltipToElement = function (element, content, position\n     const tooltipWidth = tooltipRect.width\n     const tooltipHeight = tooltipRect.height\n \n-    let tooltipX, tooltipY, arrowPositionLeft, arrowPositionTop, transform\n+    let tooltipX, tooltipY, arrowPositionLeft, arrowPositionTop, transform, relativeRect\n+    let parentRect = parentElem ? parentElem.getBoundingClientRect() : undefined\n+    if (parentRect) {\n+      relativeRect = {\n+        top: rect.top - parentRect.top,\n+        left: rect.left - parentRect.left,\n+        right: rect.right - parentRect.left,\n+        bottom: rect.bottom - parentRect.top,\n+        width: rect.width,\n+        height: rect.height,\n+      }\n+    }\n+\n+    // console.info("Hover Parent :", parentRect, "\\nChild Element :", rect,  "\\nRelative Child :", relativeRect,"\\nTooltip :", tooltipRect)\n+    console.info("Values :", relativeRect, rect)\n     const tooltipArrowSize = 10\n     if (position === "topright") {\n       tooltipX = rect.right - tooltipWidth / 2\n       tooltipY = rect.top + scrollY - (tooltipHeight + tooltipArrowSize) // + 10 for Arrow\n+      arrowPositionLeft = "50%"\n       arrowPositionTop = "100%"\n       transform = "rotate(270deg)"\n     } else if (position === "topcenter") {\n@@ -348,14 +370,15 @@ MultiSelect.prototype.addTooltipToElement = function (element, content, position\n       arrowPositionLeft = "-5px"\n       arrowPositionTop = "65%"\n     } else if (position === "rightcenter") {\n-      tooltipX = rect.right + tooltipArrowSize\n+      tooltipX = rect.right + tooltipArrowSize + 5\n       tooltipY = rect.top + scrollY + rect.height / 2 - tooltipHeight / 2\n       arrowPositionLeft = "-5px"\n       arrowPositionTop = `${rect.height / 2 - tooltipHeight / 2}px}`\n     } else if (position === "rightbottom") {\n       tooltipX = rect.right + tooltipArrowSize\n       tooltipY = rect.top + scrollY - 12\n       arrowPositionLeft = "-5px"\n+      arrowPositionTop = parentElem ? `${parentRect.height / 2 - 5}px` : `${rect.height / 2}px`\n     } else if (position === "lefttop") {\n       tooltipX = rect.left - tooltipWidth - tooltipArrowSize\n       tooltipY = rect.top + scrollY - tooltipHeight / 2\n@@ -395,7 +418,7 @@ MultiSelect.prototype.addTooltipToElement = function (element, content, position\n   })\n \n   element.addEventListener("mouseleave", () => {\n-    if (element.classList.contains("OuterFlow")) return\n+    // if (element.classList.contains("OuterFlow")) return\n     tooltip.style.display = "none"\n     tooltip.remove()\n   })\n@@ -418,7 +441,8 @@ MultiSelect.prototype.outerChipInjection = function () {\n     overflowChip.textContent = "+" + (this.selectedItems.length - 1)\n     outerContainer.appendChild(overflowChip)\n \n-    const tooltipContent = this.selectedItems.map((item) => item[this.labelKey]).join("\\n")\n+    const tooltipContent = this.selectedItems.slice(1).map((item) => item[this.labelKey]).join("\\n")\n+    this.addTooltipToElement(overflowChip, tooltipContent, "rightbottom", this.popoverBtn)\n   }\n \n   this.popoverBtn.appendChild(outerContainer)\n@@ -481,20 +505,21 @@ MultiSelect.prototype.handleItemSelection = function (element) {\n \n   const selectedItemText = element.textContent.trim()\n   const selectedItemIndex = this.unselectedItems.findIndex((x) => x[this.labelKey] === selectedItemText)\n-  const selectedItemValue = this.unselectedItems[selectedItemIndex][this.valueKey]\n-\n-  if (this.disabledFields.includes(selectedItemValue)) {\n-    return // Disable selection\n-  }\n \n   if (selectedItemIndex !== -1) {\n+    const selectedItemValue = this.unselectedItems[selectedItemIndex][this.valueKey]\n+\n+    if (this.disabledFields.includes(selectedItemValue)) {\n+      return // Disable selection\n+    }\n+\n     // Move Item From Unselected to Selected Items List\n     if (this.mode === "single") {\n-      const prev = [...this.selectedItems]\n+      const prev = this.selectedItems.length > 0 ? [...this.selectedItems][0] : ""\n       this.selectedItems = [this.unselectedItems[selectedItemIndex]] // Single select mode\n       this.unselectedItems.splice(selectedItemIndex, 1)\n-      this.unselectedItems.unshift(prev[0])\n-      console.info("prev :", prev[0])\n+      if (prev) this.unselectedItems.unshift(prev)\n+      console.info("prev :", prev)\n       this.handleBackDrop()\n     } else {\n       this.selectedItems.splice(0, 0, this.unselectedItems[selectedItemIndex])\n@@ -507,6 +532,7 @@ MultiSelect.prototype.handleItemSelection = function (element) {\n     selectedItemElement.innerHTML = `<span class="VItemLabel">${selectedItemText}</span>`\n     const crossIcon = document.createElement("img")\n     crossIcon.classList.add("VItemCrossIcon")\n+    crossIcon.style.display = this.mode === "single" ? "none" : "block"\n     crossIcon.src = "./assets/cross.svg"\n     selectedItemElement.appendChild(crossIcon)\n     this.selectedItemsContainer.appendChild(selectedItemElement)\n@@ -600,6 +626,7 @@ MultiSelect.prototype.renderSelectedItems = function (isOuterChip = false) {\n     if (!isOuterChip) {\n       const crossIcon = document.createElement("img")\n       crossIcon.classList.add("VItemCrossIcon")\n+      crossIcon.style.display = this.mode === "single" ? "none" : "block"\n       crossIcon.src = "./assets/cross.svg"\n       selectedItemElement.appendChild(crossIcon)\n     }',
    },
    {
      sha: "543cbd91ab3f6688a83a1d696db1742282e40feb",
      filename: "vlist.js",
      status: "modified",
      additions: 1,
      deletions: 0,
      changes: 1,
      blob_url: "https://github.com/Kewal89/multiselect-pure-js/blob/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/vlist.js",
      raw_url: "https://github.com/Kewal89/multiselect-pure-js/raw/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/vlist.js",
      contents_url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/contents/vlist.js?ref=03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
      patch:
        '@@ -106,6 +106,7 @@ VirtualList.createContainer = function (t, w, h) {\n   var c = t ?? document.createElement("div")\n   c.style.width = w\n   c.style.height = h\n+  c.style.minHeight = 100 + "px"\n   c.style.overflow = "auto"\n   c.style.position = "relative"\n   c.style.padding = 0',
    },
  ],
}

const gitResponse = {
  url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/compare/ceb82f60bf6e15f21161ffd9d7318a9a633000c2...03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
  html_url: "https://github.com/Kewal89/multiselect-pure-js/compare/ceb82f60bf6e15f21161ffd9d7318a9a633000c2...03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
  permalink_url: "https://github.com/Kewal89/multiselect-pure-js/compare/Kewal89:ceb82f6...Kewal89:03a7ab5",
  diff_url: "https://github.com/Kewal89/multiselect-pure-js/compare/ceb82f60bf6e15f21161ffd9d7318a9a633000c2...03a7ab5ce162cb1b27d2e46714188286e6c9aa3f.diff",
  patch_url: "https://github.com/Kewal89/multiselect-pure-js/compare/ceb82f60bf6e15f21161ffd9d7318a9a633000c2...03a7ab5ce162cb1b27d2e46714188286e6c9aa3f.patch",
  base_commit: {
    sha: "ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
    node_id: "C_kwDOKDf_u9oAKGNlYjgyZjYwYmY2ZTE1ZjIxMTYxZmZkOWQ3MzE4YTlhNjMzMDAwYzI",
    commit: {
      author: {
        name: "Kewal Rathod",
        email: "kewalrathod8@gmail.com",
        date: "2023-08-09T16:10:11Z",
      },
      committer: {
        name: "Kewal Rathod",
        email: "kewalrathod8@gmail.com",
        date: "2023-08-09T16:10:11Z",
      },
      message: "* Fixed Issue where values were not setting if no default were passed.",
      tree: {
        sha: "63168fa291a17a0eb6f37427a915c37cc6625f99",
        url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/git/trees/63168fa291a17a0eb6f37427a915c37cc6625f99",
      },
      url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/git/commits/ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
      comment_count: 0,
      verification: {
        verified: false,
        reason: "unsigned",
        signature: null,
        payload: null,
      },
    },
    url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/commits/ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
    html_url: "https://github.com/Kewal89/multiselect-pure-js/commit/ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
    comments_url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/commits/ceb82f60bf6e15f21161ffd9d7318a9a633000c2/comments",
    author: {
      login: "Kewal89",
      id: 43823249,
      node_id: "MDQ6VXNlcjQzODIzMjQ5",
      avatar_url: "https://avatars.githubusercontent.com/u/43823249?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Kewal89",
      html_url: "https://github.com/Kewal89",
      followers_url: "https://api.github.com/users/Kewal89/followers",
      following_url: "https://api.github.com/users/Kewal89/following{/other_user}",
      gists_url: "https://api.github.com/users/Kewal89/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Kewal89/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Kewal89/subscriptions",
      organizations_url: "https://api.github.com/users/Kewal89/orgs",
      repos_url: "https://api.github.com/users/Kewal89/repos",
      events_url: "https://api.github.com/users/Kewal89/events{/privacy}",
      received_events_url: "https://api.github.com/users/Kewal89/received_events",
      type: "User",
      site_admin: false,
    },
    committer: {
      login: "Kewal89",
      id: 43823249,
      node_id: "MDQ6VXNlcjQzODIzMjQ5",
      avatar_url: "https://avatars.githubusercontent.com/u/43823249?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Kewal89",
      html_url: "https://github.com/Kewal89",
      followers_url: "https://api.github.com/users/Kewal89/followers",
      following_url: "https://api.github.com/users/Kewal89/following{/other_user}",
      gists_url: "https://api.github.com/users/Kewal89/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Kewal89/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Kewal89/subscriptions",
      organizations_url: "https://api.github.com/users/Kewal89/orgs",
      repos_url: "https://api.github.com/users/Kewal89/repos",
      events_url: "https://api.github.com/users/Kewal89/events{/privacy}",
      received_events_url: "https://api.github.com/users/Kewal89/received_events",
      type: "User",
      site_admin: false,
    },
    parents: [
      {
        sha: "a04e57575521072fe2a7892e290ecc2129304bf5",
        url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/commits/a04e57575521072fe2a7892e290ecc2129304bf5",
        html_url: "https://github.com/Kewal89/multiselect-pure-js/commit/a04e57575521072fe2a7892e290ecc2129304bf5",
      },
    ],
  },
  merge_base_commit: {
    sha: "ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
    node_id: "C_kwDOKDf_u9oAKGNlYjgyZjYwYmY2ZTE1ZjIxMTYxZmZkOWQ3MzE4YTlhNjMzMDAwYzI",
    commit: {
      author: {
        name: "Kewal Rathod",
        email: "kewalrathod8@gmail.com",
        date: "2023-08-09T16:10:11Z",
      },
      committer: {
        name: "Kewal Rathod",
        email: "kewalrathod8@gmail.com",
        date: "2023-08-09T16:10:11Z",
      },
      message: "* Fixed Issue where values were not setting if no default were passed.",
      tree: {
        sha: "63168fa291a17a0eb6f37427a915c37cc6625f99",
        url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/git/trees/63168fa291a17a0eb6f37427a915c37cc6625f99",
      },
      url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/git/commits/ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
      comment_count: 0,
      verification: {
        verified: false,
        reason: "unsigned",
        signature: null,
        payload: null,
      },
    },
    url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/commits/ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
    html_url: "https://github.com/Kewal89/multiselect-pure-js/commit/ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
    comments_url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/commits/ceb82f60bf6e15f21161ffd9d7318a9a633000c2/comments",
    author: {
      login: "Kewal89",
      id: 43823249,
      node_id: "MDQ6VXNlcjQzODIzMjQ5",
      avatar_url: "https://avatars.githubusercontent.com/u/43823249?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Kewal89",
      html_url: "https://github.com/Kewal89",
      followers_url: "https://api.github.com/users/Kewal89/followers",
      following_url: "https://api.github.com/users/Kewal89/following{/other_user}",
      gists_url: "https://api.github.com/users/Kewal89/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Kewal89/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Kewal89/subscriptions",
      organizations_url: "https://api.github.com/users/Kewal89/orgs",
      repos_url: "https://api.github.com/users/Kewal89/repos",
      events_url: "https://api.github.com/users/Kewal89/events{/privacy}",
      received_events_url: "https://api.github.com/users/Kewal89/received_events",
      type: "User",
      site_admin: false,
    },
    committer: {
      login: "Kewal89",
      id: 43823249,
      node_id: "MDQ6VXNlcjQzODIzMjQ5",
      avatar_url: "https://avatars.githubusercontent.com/u/43823249?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/Kewal89",
      html_url: "https://github.com/Kewal89",
      followers_url: "https://api.github.com/users/Kewal89/followers",
      following_url: "https://api.github.com/users/Kewal89/following{/other_user}",
      gists_url: "https://api.github.com/users/Kewal89/gists{/gist_id}",
      starred_url: "https://api.github.com/users/Kewal89/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/Kewal89/subscriptions",
      organizations_url: "https://api.github.com/users/Kewal89/orgs",
      repos_url: "https://api.github.com/users/Kewal89/repos",
      events_url: "https://api.github.com/users/Kewal89/events{/privacy}",
      received_events_url: "https://api.github.com/users/Kewal89/received_events",
      type: "User",
      site_admin: false,
    },
    parents: [
      {
        sha: "a04e57575521072fe2a7892e290ecc2129304bf5",
        url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/commits/a04e57575521072fe2a7892e290ecc2129304bf5",
        html_url: "https://github.com/Kewal89/multiselect-pure-js/commit/a04e57575521072fe2a7892e290ecc2129304bf5",
      },
    ],
  },
  status: "ahead",
  ahead_by: 1,
  behind_by: 0,
  total_commits: 1,
  commits: [
    {
      sha: "03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
      node_id: "C_kwDOKDf_u9oAKDAzYTdhYjVjZTE2MmNiMWIyN2QyZTQ2NzE0MTg4Mjg2ZTZjOWFhM2Y",
      commit: {
        author: {
          name: "Kewal Rathod",
          email: "kewalrathod8@gmail.com",
          date: "2023-08-10T11:18:08Z",
        },
        committer: {
          name: "Kewal Rathod",
          email: "kewalrathod8@gmail.com",
          date: "2023-08-10T11:18:08Z",
        },
        message: "* Fixed issues with Single Select.",
        tree: {
          sha: "c9f38b2dfe6698106f9a9326cdbd1b575e5d8c79",
          url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/git/trees/c9f38b2dfe6698106f9a9326cdbd1b575e5d8c79",
        },
        url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/git/commits/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
        comment_count: 0,
        verification: {
          verified: false,
          reason: "unsigned",
          signature: null,
          payload: null,
        },
      },
      url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/commits/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
      html_url: "https://github.com/Kewal89/multiselect-pure-js/commit/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
      comments_url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/commits/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/comments",
      author: {
        login: "Kewal89",
        id: 43823249,
        node_id: "MDQ6VXNlcjQzODIzMjQ5",
        avatar_url: "https://avatars.githubusercontent.com/u/43823249?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/Kewal89",
        html_url: "https://github.com/Kewal89",
        followers_url: "https://api.github.com/users/Kewal89/followers",
        following_url: "https://api.github.com/users/Kewal89/following{/other_user}",
        gists_url: "https://api.github.com/users/Kewal89/gists{/gist_id}",
        starred_url: "https://api.github.com/users/Kewal89/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/Kewal89/subscriptions",
        organizations_url: "https://api.github.com/users/Kewal89/orgs",
        repos_url: "https://api.github.com/users/Kewal89/repos",
        events_url: "https://api.github.com/users/Kewal89/events{/privacy}",
        received_events_url: "https://api.github.com/users/Kewal89/received_events",
        type: "User",
        site_admin: false,
      },
      committer: {
        login: "Kewal89",
        id: 43823249,
        node_id: "MDQ6VXNlcjQzODIzMjQ5",
        avatar_url: "https://avatars.githubusercontent.com/u/43823249?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/Kewal89",
        html_url: "https://github.com/Kewal89",
        followers_url: "https://api.github.com/users/Kewal89/followers",
        following_url: "https://api.github.com/users/Kewal89/following{/other_user}",
        gists_url: "https://api.github.com/users/Kewal89/gists{/gist_id}",
        starred_url: "https://api.github.com/users/Kewal89/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/Kewal89/subscriptions",
        organizations_url: "https://api.github.com/users/Kewal89/orgs",
        repos_url: "https://api.github.com/users/Kewal89/repos",
        events_url: "https://api.github.com/users/Kewal89/events{/privacy}",
        received_events_url: "https://api.github.com/users/Kewal89/received_events",
        type: "User",
        site_admin: false,
      },
      parents: [
        {
          sha: "ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
          url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/commits/ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
          html_url: "https://github.com/Kewal89/multiselect-pure-js/commit/ceb82f60bf6e15f21161ffd9d7318a9a633000c2",
        },
      ],
    },
  ],
  files: [
    {
      sha: "aba9f24292849492f4a5ec3743a9a1fb01d2c6cd",
      filename: "index.html",
      status: "modified",
      additions: 4,
      deletions: 3,
      changes: 7,
      blob_url: "https://github.com/Kewal89/multiselect-pure-js/blob/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/index.html",
      raw_url: "https://github.com/Kewal89/multiselect-pure-js/raw/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/index.html",
      contents_url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/contents/index.html?ref=03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
      patch:
        '@@ -52,7 +52,7 @@\n           }\n         })\n \n-        const itemList3 = Array.from({ length: 100000 }, (_, i) => {\n+        const itemList3 = Array.from({ length: 2 }, (_, i) => {\n           return {\n             index: i,\n             label: `Item ${i}`,\n@@ -134,14 +134,15 @@\n           items: itemList3,\n           rootElement: ".MultiSelectContainer_3",\n           disabledFields: [31, 32, 33, 34],\n-          defaultSelected: [0, 1, 2, 3, 4, 5, 6],\n+          defaultSelected: [0, 1, 2, 3, 4, 5],\n+          mode: "single",\n+          debug: true,\n         })\n         multiSelect4 = new MultiSelect({\n           items: itemList4,\n           rootElement: ".MultiSelectContainer_4",\n           mode: "single",\n           defaultSelected: [0],\n-          debug: true,\n         })\n         multiSelect5 = new MultiSelect({\n           items: itemList3,',
    },
    {
      sha: "748d66ad26de2cf09b8ceb224148ca3e4cb2a481",
      filename: "multiselect.css",
      status: "modified",
      additions: 2,
      deletions: 2,
      changes: 4,
      blob_url: "https://github.com/Kewal89/multiselect-pure-js/blob/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/multiselect.css",
      raw_url: "https://github.com/Kewal89/multiselect-pure-js/raw/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/multiselect.css",
      contents_url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/contents/multiselect.css?ref=03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
      patch:
        "@@ -319,9 +319,9 @@\n   color: #B5BDC1;\n }\n \n-.MultiSelectList .VItem:last-child:hover {\n+/* .MultiSelectList .VItem:last-child:hover {\n   border-radius: 0 0 8px 8px;\n-}\n+} */\n \n .MultiSelectList .VItem:hover {\n   background: #E7E9EA;",
    },
    {
      sha: "7ee41e8994b3cae7f8a4b36e73ac65d31c9cff50",
      filename: "multiselect.js",
      status: "modified",
      additions: 44,
      deletions: 17,
      changes: 61,
      blob_url: "https://github.com/Kewal89/multiselect-pure-js/blob/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/multiselect.js",
      raw_url: "https://github.com/Kewal89/multiselect-pure-js/raw/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/multiselect.js",
      contents_url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/contents/multiselect.js?ref=03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
      patch:
        '@@ -39,6 +39,10 @@ function MultiSelect(props) {\n   this.unselectedItems = Array.isArray(this.defaultSelected) && this.defaultSelected.length > 0 ? [] : [...this.itemList]\n   // TODO: Handle This Error Properly As It May Crash Rest of The Code.\n   if (!Array.isArray(this.itemList)) console.error("Item List should be an array.", this.root)\n+  if (this.mode === "single" && this.defaultSelected.length > 1) {\n+    this.defaultSelected = [this.defaultSelected[0]]\n+    console.error("Single Select Accepts only 1 value in defaultSelected")\n+  }\n \n   this.initialize()\n   multiSelectInstances.set(this.rootContainer, this)\n@@ -68,9 +72,12 @@ MultiSelect.prototype.recalculateHeight = function () {\n     else isClearAll.classList.add("Inactive")\n   }\n \n-  if (!this.chipCollapse || this.selectedItems.length < this.collapseChipCount) return false\n-  const height = this.popperContainer.querySelector(".ChipsList").offsetHeight\n-  this.unselectedItemsContainer.style.height = `${this.height - height}px`\n+  if (!this.chipCollapse) return false\n+  var height = 400\n+  if (this.itemList.length < 10) height = this.itemList.length * 40\n+  else height = this.height - this.popperContainer.querySelector(".ChipsList").offsetHeight\n+\n+  this.unselectedItemsContainer.style.height = `${height}px`\n }\n \n MultiSelect.prototype.generateDOM = function () {\n@@ -232,7 +239,7 @@ MultiSelect.prototype.setupEventListeners = function () {\n     self.backdropElement.classList.toggle("Show", !isOpen)\n \n     if (self.virtualList) {\n-      self.refreshList()\n+      // self.refreshList()\n     }\n   }\n \n@@ -266,7 +273,7 @@ MultiSelect.prototype.setupEventListeners = function () {\n       if (!self.outerLabelCollapse) self.renderSelectedItems() // No Overflow\n     } else if (event.target.classList.contains("VItem") && !event.target.closest(".ChipsList")) {\n       self.handleItemSelection(event.target)\n-    } else if (event.target.classList.contains("VItemCrossIcon")) {\n+    } else if (event.target.classList.contains("VItemCrossIcon") && self.mode === "multi") {\n       self.handleItemUnselection(event.target.closest(".VItem"))\n     } else if (self.mode === "multi" && event.target === self.selectAllBtn && self.selectAllExpose) {\n       self.selectAllItems()\n@@ -305,11 +312,26 @@ MultiSelect.prototype.addTooltipToElement = function (element, content, position\n     const tooltipWidth = tooltipRect.width\n     const tooltipHeight = tooltipRect.height\n \n-    let tooltipX, tooltipY, arrowPositionLeft, arrowPositionTop, transform\n+    let tooltipX, tooltipY, arrowPositionLeft, arrowPositionTop, transform, relativeRect\n+    let parentRect = parentElem ? parentElem.getBoundingClientRect() : undefined\n+    if (parentRect) {\n+      relativeRect = {\n+        top: rect.top - parentRect.top,\n+        left: rect.left - parentRect.left,\n+        right: rect.right - parentRect.left,\n+        bottom: rect.bottom - parentRect.top,\n+        width: rect.width,\n+        height: rect.height,\n+      }\n+    }\n+\n+    // console.info("Hover Parent :", parentRect, "\\nChild Element :", rect,  "\\nRelative Child :", relativeRect,"\\nTooltip :", tooltipRect)\n+    console.info("Values :", relativeRect, rect)\n     const tooltipArrowSize = 10\n     if (position === "topright") {\n       tooltipX = rect.right - tooltipWidth / 2\n       tooltipY = rect.top + scrollY - (tooltipHeight + tooltipArrowSize) // + 10 for Arrow\n+      arrowPositionLeft = "50%"\n       arrowPositionTop = "100%"\n       transform = "rotate(270deg)"\n     } else if (position === "topcenter") {\n@@ -348,14 +370,15 @@ MultiSelect.prototype.addTooltipToElement = function (element, content, position\n       arrowPositionLeft = "-5px"\n       arrowPositionTop = "65%"\n     } else if (position === "rightcenter") {\n-      tooltipX = rect.right + tooltipArrowSize\n+      tooltipX = rect.right + tooltipArrowSize + 5\n       tooltipY = rect.top + scrollY + rect.height / 2 - tooltipHeight / 2\n       arrowPositionLeft = "-5px"\n       arrowPositionTop = `${rect.height / 2 - tooltipHeight / 2}px}`\n     } else if (position === "rightbottom") {\n       tooltipX = rect.right + tooltipArrowSize\n       tooltipY = rect.top + scrollY - 12\n       arrowPositionLeft = "-5px"\n+      arrowPositionTop = parentElem ? `${parentRect.height / 2 - 5}px` : `${rect.height / 2}px`\n     } else if (position === "lefttop") {\n       tooltipX = rect.left - tooltipWidth - tooltipArrowSize\n       tooltipY = rect.top + scrollY - tooltipHeight / 2\n@@ -395,7 +418,7 @@ MultiSelect.prototype.addTooltipToElement = function (element, content, position\n   })\n \n   element.addEventListener("mouseleave", () => {\n-    if (element.classList.contains("OuterFlow")) return\n+    // if (element.classList.contains("OuterFlow")) return\n     tooltip.style.display = "none"\n     tooltip.remove()\n   })\n@@ -418,7 +441,8 @@ MultiSelect.prototype.outerChipInjection = function () {\n     overflowChip.textContent = "+" + (this.selectedItems.length - 1)\n     outerContainer.appendChild(overflowChip)\n \n-    const tooltipContent = this.selectedItems.map((item) => item[this.labelKey]).join("\\n")\n+    const tooltipContent = this.selectedItems.slice(1).map((item) => item[this.labelKey]).join("\\n")\n+    this.addTooltipToElement(overflowChip, tooltipContent, "rightbottom", this.popoverBtn)\n   }\n \n   this.popoverBtn.appendChild(outerContainer)\n@@ -481,20 +505,21 @@ MultiSelect.prototype.handleItemSelection = function (element) {\n \n   const selectedItemText = element.textContent.trim()\n   const selectedItemIndex = this.unselectedItems.findIndex((x) => x[this.labelKey] === selectedItemText)\n-  const selectedItemValue = this.unselectedItems[selectedItemIndex][this.valueKey]\n-\n-  if (this.disabledFields.includes(selectedItemValue)) {\n-    return // Disable selection\n-  }\n \n   if (selectedItemIndex !== -1) {\n+    const selectedItemValue = this.unselectedItems[selectedItemIndex][this.valueKey]\n+\n+    if (this.disabledFields.includes(selectedItemValue)) {\n+      return // Disable selection\n+    }\n+\n     // Move Item From Unselected to Selected Items List\n     if (this.mode === "single") {\n-      const prev = [...this.selectedItems]\n+      const prev = this.selectedItems.length > 0 ? [...this.selectedItems][0] : ""\n       this.selectedItems = [this.unselectedItems[selectedItemIndex]] // Single select mode\n       this.unselectedItems.splice(selectedItemIndex, 1)\n-      this.unselectedItems.unshift(prev[0])\n-      console.info("prev :", prev[0])\n+      if (prev) this.unselectedItems.unshift(prev)\n+      console.info("prev :", prev)\n       this.handleBackDrop()\n     } else {\n       this.selectedItems.splice(0, 0, this.unselectedItems[selectedItemIndex])\n@@ -507,6 +532,7 @@ MultiSelect.prototype.handleItemSelection = function (element) {\n     selectedItemElement.innerHTML = `<span class="VItemLabel">${selectedItemText}</span>`\n     const crossIcon = document.createElement("img")\n     crossIcon.classList.add("VItemCrossIcon")\n+    crossIcon.style.display = this.mode === "single" ? "none" : "block"\n     crossIcon.src = "./assets/cross.svg"\n     selectedItemElement.appendChild(crossIcon)\n     this.selectedItemsContainer.appendChild(selectedItemElement)\n@@ -600,6 +626,7 @@ MultiSelect.prototype.renderSelectedItems = function (isOuterChip = false) {\n     if (!isOuterChip) {\n       const crossIcon = document.createElement("img")\n       crossIcon.classList.add("VItemCrossIcon")\n+      crossIcon.style.display = this.mode === "single" ? "none" : "block"\n       crossIcon.src = "./assets/cross.svg"\n       selectedItemElement.appendChild(crossIcon)\n     }',
    },
    {
      sha: "543cbd91ab3f6688a83a1d696db1742282e40feb",
      filename: "vlist.js",
      status: "modified",
      additions: 1,
      deletions: 0,
      changes: 1,
      blob_url: "https://github.com/Kewal89/multiselect-pure-js/blob/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/vlist.js",
      raw_url: "https://github.com/Kewal89/multiselect-pure-js/raw/03a7ab5ce162cb1b27d2e46714188286e6c9aa3f/vlist.js",
      contents_url: "https://api.github.com/repos/Kewal89/multiselect-pure-js/contents/vlist.js?ref=03a7ab5ce162cb1b27d2e46714188286e6c9aa3f",
      patch:
        '@@ -106,6 +106,7 @@ VirtualList.createContainer = function (t, w, h) {\n   var c = t ?? document.createElement("div")\n   c.style.width = w\n   c.style.height = h\n+  c.style.minHeight = 100 + "px"\n   c.style.overflow = "auto"\n   c.style.position = "relative"\n   c.style.padding = 0',
    },
  ],
}

module.exports = { gitResponse, baseGitResponse }
